version: '2'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - '127.0.0.1:6379:6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PORT=7000
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - '127.0.0.1:7000:7000'
    depends_on:
      - redis-master
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - '127.0.0.1:26379:26379'
